### ISSUE TITLE
Copyright and license terms

### ISSUE THREAD

**Issue by ibinti** [gtache/scalajs-gradle#14]
If you are the original writer, could you please add copyright and license terms?
They seem missing.
Uncertainty prevents me from forking.

**Comment by raiju** [comment]
Not the author, but there is a license block in the gradle file https://github.com/gtache/scalajs-gradle/blob/master/scalajs-plugin/build.gradle#L86

**Comment by ibinti** [comment]
Ahhh, got it. thanks
